In [35]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsClassifier 
import matplotlib.pyplot as plt  
import seaborn as sns 

In [37]:
df = pd.read_csv("Maternal_Health.csv")
print(df.head())
df['Risk'] = pd.factorize(df['RiskLevel'])[0]
df.drop('RiskLevel', axis=1, inplace=True)
print(df.head())
X = df.drop('Risk', axis=1) 
y = df['Risk']

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk
   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  Risk
0   25         130           80  15.0      98.0         86     0
1   35         140           90  13.0      98.0         70     0
2   29          90           70   8.0     100.0         80     0
3   30         140           85   7.0      98.0         70     0
4   35         120           60   6.1      98.0         76     1


In [39]:
K = [] 
training = [] 
test = [] 
scores = {} 
  
for k in range(2, 21): 
    clf = KNeighborsClassifier(n_neighbors = k) 
    clf.fit(X_train, y_train) 
  
    training_score = clf.score(X_train, y_train) 
    test_score = clf.score(X_test, y_test) 
    K.append(k) 
  
    training.append(training_score) 
    test.append(test_score) 
    scores[k] = [training_score, test_score] 


In [41]:
for keys, values in scores.items(): 
    print(keys, ':', values) 

2 : [0.8865598027127004, 0.729064039408867]
3 : [0.8927250308261405, 0.7241379310344828]
4 : [0.815043156596794, 0.6502463054187192]
5 : [0.7866831072749692, 0.6945812807881774]
6 : [0.7583230579531443, 0.6896551724137931]
7 : [0.7669543773119606, 0.6798029556650246]
8 : [0.749691738594328, 0.6551724137931034]
9 : [0.752157829839704, 0.645320197044335]
10 : [0.7127003699136868, 0.6108374384236454]
11 : [0.7163995067817509, 0.6403940886699507]
12 : [0.7151664611590629, 0.6354679802955665]
13 : [0.7003699136868065, 0.6305418719211823]
14 : [0.6991368680641183, 0.6403940886699507]
15 : [0.7003699136868065, 0.6206896551724138]
16 : [0.7016029593094945, 0.6403940886699507]
17 : [0.6905055487053021, 0.6354679802955665]
18 : [0.6966707768187423, 0.6354679802955665]
19 : [0.6991368680641183, 0.6354679802955665]
20 : [0.6979038224414303, 0.625615763546798]


In [49]:
# Predict on the test set
y_pred = clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.625615763546798
Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.66      0.70        47
           1       0.57      0.74      0.64        80
           2       0.65      0.49      0.56        76

    accuracy                           0.63       203
   macro avg       0.65      0.63      0.63       203
weighted avg       0.64      0.63      0.62       203

Confusion Matrix:
[[31 11  5]
 [ 6 59 15]
 [ 5 34 37]]
